from pathlib import Path

from app.models.registry_types import ModelCapabilities, ModelDescriptor
from app.services.model_adapter import ModelAdapter


class FakeAdapter(ModelAdapter):
    """A torch-free adapter for contract-compliance tests."""

    def __init__(self, descriptor):
        super().__init__(descriptor)
        self.installed = False
        self.loaded = False
        self.generate_calls: list[str] = []

    async def install(self) -> None:
        self.installed = True

    async def load(self) -> None:
        self.loaded = True

    def unload(self) -> None:
        self.loaded = False

    async def health_check(self) -> bool:
        return self.loaded

    async def generate(self, *, text, output_path, **kwargs):
        self.generate_calls.append(text)
        return (1.5, [f"generated by {self.model_id}"])

    async def clone_voice(self, *, db, voice, reference_audio_key):
        return ("variant", self.model_id)

    async def build_variant(self, *, db, voice):
        return ("variant", self.model_id)


def _descriptor():
    return ModelDescriptor(
        id="fake-1", name="Fake", description="d", provider="fake",
        supported_languages=["en", "pt"], supported_tags=["happy", "sad"],
        capabilities=ModelCapabilities(supports_singing=True),
    )


def test_data_methods_come_from_descriptor():
    a = FakeAdapter(_descriptor())
    assert a.model_id == "fake-1"
    assert a.get_capabilities().supports_singing is True
    assert a.get_supported_languages() == ["en", "pt"]
    assert a.get_supported_tags() == ["happy", "sad"]


async def test_lifecycle_and_generate_contract():
    a = FakeAdapter(_descriptor())
    await a.install()
    assert a.installed
    await a.load()
    assert await a.health_check() is True
    duration, logs = await a.generate(text="hi", output_path=Path("/tmp/x.wav"))
    assert duration == 1.5 and "fake-1" in logs[0]
    a.unload()
    assert await a.health_check() is False


def test_fake_is_a_model_adapter():
    assert isinstance(FakeAdapter(_descriptor()), ModelAdapter)
